name: communication_client
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

# flutter packages pub run build_runner build --delete-conflicting-outputs

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  injectable: ^1.5.3
  get_it: ^7.2.0
  injectable_generator: ^1.5.4
  freezed: ^2.1.0+1
  freezed_annotation: ^2.1.0
  json_serializable: ^6.5.1
  dio: ^4.0.6
  pretty_dio_logger: ^1.1.1
  flutter_bloc: ^8.1.1
  hydrated_bloc: ^8.1.0
  path_provider: ^2.0.11
  flutter_secure_storage: ^7.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Black.ttf
          weight: 900
          style: normal
        - asset: fonts/Lato-Bold.ttf
          weight: 700
          style: normal
        - asset: fonts/Lato-Regular.ttf
          weight: 400
          style: normal
        - asset: fonts/Lato-Light.ttf
          weight: 300
          style: normal
        - asset: fonts/Lato-Thin.ttf
          weight: 100
          style: normal
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans.ttf
          weight: 400
          style: normal
        - asset: fonts/OpenSans-Italic.ttf
          weight: 400
          style: italic
    - family: ProximaNova
      fonts:
        - asset: fonts/proximanova_black.ttf
          weight: 900
          style: normal
        - asset: fonts/proximanova_regular.ttf
          weight: 400
          style: normal
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Black.ttf
          weight: 900
          style: normal
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
          style: normal
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
          style: normal
        - asset: fonts/Roboto-Light.ttf
          weight: 300
          style: normal
        - asset: fonts/Roboto-Thin.ttf
          weight: 100
          style: normal
    - family: RedHatDisplay
      fonts:
        - asset: fonts/RedHatDisplay-Black.ttf
          weight: 900
          style: normal
        - asset: fonts/RedHatDisplay-Bold.ttf
          weight: 700
          style: normal
        - asset: fonts/RedHatDisplay-Regular.ttf
          weight: 400
          style: normal
        - asset: fonts/RedHatDisplay-Light.ttf
          weight: 300
          style: normal
