name: communication_client
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: '^3.1.0'

# flutter packages pub run build_runner build --delete-conflicting-outputs

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # di
  injectable: ^2.3.2
  get_it: ^7.2.0
  injectable_generator: ^2.4.1
  # serialization and codogeneration
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1
  # http client
  dio: ^5.4.0
  # logger
  pretty_dio_logger: ^1.1.1
  # state manager
  provider: ^6.1.1
  flutter_bloc: ^8.1.3
  bloc_concurrency: ^0.2.2
  # storage
  hydrated_bloc: ^9.1.3
  path_provider: ^2.0.11
  # flutter_secure_storage: ^9.0.0
  # webrtc
  flutter_webrtc: ^0.9.47
  # firebase
  firebase_core: ^2.10.0
  cloud_firestore: ^4.5.3
  cloud_firestore_web: ^3.4.2
  # checks for an active internet connection
  internet_connection_checker: ^1.0.0+1
  # loading indicators
  flutter_spinkit: ^5.2.0
  # utils
  # modal_bottom_sheet: ^2.1.2
  share_plus: ^6.3.0
  flutter_staggered_grid_view: ^0.7.0
  helpers: ^1.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Black.ttf
          weight: 900
          style: normal
        - asset: fonts/Lato-Bold.ttf
          weight: 700
          style: normal
        - asset: fonts/Lato-Regular.ttf
          weight: 400
          style: normal
        - asset: fonts/Lato-Light.ttf
          weight: 300
          style: normal
        - asset: fonts/Lato-Thin.ttf
          weight: 100
          style: normal
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans.ttf
          weight: 400
          style: normal
        - asset: fonts/OpenSans-Italic.ttf
          weight: 400
          style: italic
    - family: ProximaNova
      fonts:
        - asset: fonts/proximanova_black.ttf
          weight: 900
          style: normal
        - asset: fonts/proximanova_regular.ttf
          weight: 400
          style: normal
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Black.ttf
          weight: 900
          style: normal
        - asset: fonts/Roboto-Bold.ttf
          weight: 700
          style: normal
        - asset: fonts/Roboto-Regular.ttf
          weight: 400
          style: normal
        - asset: fonts/Roboto-Light.ttf
          weight: 300
          style: normal
        - asset: fonts/Roboto-Thin.ttf
          weight: 100
          style: normal
    - family: RedHatDisplay
      fonts:
        - asset: fonts/RedHatDisplay-Black.ttf
          weight: 900
          style: normal
        - asset: fonts/RedHatDisplay-Bold.ttf
          weight: 700
          style: normal
        - asset: fonts/RedHatDisplay-Regular.ttf
          weight: 400
          style: normal
        - asset: fonts/RedHatDisplay-Light.ttf
          weight: 300
          style: normal
    - family: SF_Text
      fonts:
        - asset: fonts/Inter-Black.ttf
          weight: 900
          style: normal
        - asset: fonts/Inter-ExtraBold.ttf
          weight: 800
          style: normal
        - asset: fonts/Inter-Bold.ttf
          weight: 700
          style: normal
        - asset: fonts/Inter-SemiBold.ttf
          weight: 600
          style: normal
        - asset: fonts/Inter-Medium.ttf
          weight: 500
          style: normal
        - asset: fonts/Inter-Regular.ttf
          weight: 400
          style: normal
        - asset: fonts/Inter-Light.ttf
          weight: 300
          style: normal
        - asset: fonts/Inter-ExtraLight.ttf
          weight: 200
          style: normal
        - asset: fonts/Inter-Thin.ttf
          weight: 100
          style: normal

    - family: CustomIcon
      fonts:
        - asset: fonts/CustomIcon.ttf
