// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_7pXFErPLv0ue6-Xgb_FX8uGfh31Di9U',
    appId: '1:310857209897:web:336125bc9479c42e8a2438',
    messagingSenderId: '310857209897',
    projectId: 'communication-1cbb7',
    authDomain: 'communication-1cbb7.firebaseapp.com',
    storageBucket: 'communication-1cbb7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeyt3e2143bhEaUzZyL4n0_4Wsqb1EqYg',
    appId: '1:310857209897:android:c5efc55f249e470d8a2438',
    messagingSenderId: '310857209897',
    projectId: 'communication-1cbb7',
    storageBucket: 'communication-1cbb7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHqQzqTlHF8J4L4pPMfoWyP6noPUPqMqU',
    appId: '1:310857209897:ios:b4e633cd3e66e8638a2438',
    messagingSenderId: '310857209897',
    projectId: 'communication-1cbb7',
    storageBucket: 'communication-1cbb7.appspot.com',
    iosClientId: '310857209897-fq842eth2qome2prd237kqmtthaah25h.apps.googleusercontent.com',
    iosBundleId: 'com.example.communicationClient',
  );
}
